name: "Build & test nickel-kubernetes"
on:
  - pull_request
  - push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix config check || nix doctor
    - run: nix flake check
    # disabled- uses too much disk space on the runner.
    # - run: nix build
